export default {
    backgroungColor: 'white',
    backgroundTag: '#78e3fd',
    backgroundItem: '#d1f5ff',
    backgroundButton: '#7d53de',
    textDescription: 'black',
    textDate: 'black',
    textAddress: 'black',
    textTag: 'black',
    gray1: '#f5f5f5',
    gray2: '#eeeeee',
    gray3: '#e0e0e0',
    gray4: '#dbdbdb',
    teal1: '#b2ebf2',
    teal2: '#80deea',
    teal3: '#4dd0e1',
    teal4: '#26c6da',
    teal5: '#00bcd4',
}